### ISSUE TITLE
MP4.bt - plyparser.ParseError: <string>:1:1: before: /

### ISSUE THREAD

**Issue by RagingPotatoz** [d0c-s4vage/py010parser#17]
Here is call trace up until another module interp.py

`  File "/usr/local/lib/python2.7/dist-packages/py010parser/__init__.py", line 90, in parse_string
    keep_scopes     = keep_scopes
  File "/usr/local/lib/python2.7/dist-packages/py010parser/c_parser.py", line 178, in parse
    debug=debuglevel)
  File "/usr/local/lib/python2.7/dist-packages/py010parser/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/usr/local/lib/python2.7/dist-packages/py010parser/ply/yacc.py", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/usr/local/lib/python2.7/dist-packages/py010parser/c_parser.py", line 1952, in p_error
    column=self.clex.find_tok_column(p)))
  File "/usr/local/lib/python2.7/dist-packages/py010parser/plyparser.py", line 54, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
py010parser.plyparser.ParseError: <string>:1:1: before: /
`

Here is example of code

`dom = pfp.parse(data_file=data,template=temp_)
`

I will attach the Template file as well for this error 
[MP4.txt](https://github.com/d0c-s4vage/py010parser/files/745661/MP4.txt)

**Comment by d0c-s4vage** [comment]
We aren't getting parse errors on this one anymore, some built-in 010 editor functionality isn't yet implemented:

```
$> pfp -t tests/templates/MP4.bt /home/james/Downloads/test_video.mp4
Traceback (most recent call last):
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 965, in _run
    res = self._handle_node(self._ast, None, None, self._stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 1074, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 1117, in _handle_file_ast
    self._handle_node(child, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 1074, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 2341, in _handle_while
    self._handle_node(node.stmt, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 1074, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 2155, in _handle_compound
    self._handle_node(child, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 1074, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 1339, in _handle_decl
    field._pfp__init(stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 126, in _pfp__init
    self._pfp__interp._handle_node(decls, ctxt=self, stream=stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 1074, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 1636, in _handle_struct_decls
    self._handle_node(decl, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 1074, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 2283, in _handle_if
    cond = self._handle_node(node.cond, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 1074, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 1802, in _handle_binary_op
    left_val = self._handle_node(node.left, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 1074, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 2122, in _handle_func_call
    return func.call(func_args, ctxt, scope, stream, self, node.coord)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/functions.py", line 79, in call
    res = self.func(args, ctxt, scope, stream, coord)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/native/compat_string.py", line 140, in Memcmp
    raise NotImplementedError()
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/venv3/bin/pfp", line 8, in <module>
    sys.exit(main())
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/__main__.py", line 55, in main
    keep_successful=args.keep,
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/__init__.py", line 91, in parse
    printf=printf,
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 788, in parse
    res = self._run(keep_successful)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 992, in _run
    traceback,
  File "/tmp/venv3/lib/python3.6/site-packages/six.py", line 695, in reraise
    raise value.with_traceback(tb)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 965, in _run
    res = self._handle_node(self._ast, None, None, self._stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 1074, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 1117, in _handle_file_ast
    self._handle_node(child, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 1074, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 2341, in _handle_while
    self._handle_node(node.stmt, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 1074, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 2155, in _handle_compound
    self._handle_node(child, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 1074, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 1339, in _handle_decl
    field._pfp__init(stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 126, in _pfp__init
    self._pfp__interp._handle_node(decls, ctxt=self, stream=stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 1074, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 1636, in _handle_struct_decls
    self._handle_node(decl, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 1074, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 2283, in _handle_if
    cond = self._handle_node(node.cond, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 1074, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 1802, in _handle_binary_op
    left_val = self._handle_node(node.left, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 1074, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/interp.py", line 2122, in _handle_func_call
    return func.call(func_args, ctxt, scope, stream, self, node.coord)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/functions.py", line 79, in call
    res = self.func(args, ctxt, scope, stream, coord)
  File "/tmp/venv3/lib/python3.6/site-packages/pfp/native/compat_string.py", line 140, in Memcmp
    raise NotImplementedError()
pfp.errors.PfpError:
Exception at tests/templates/MP4.bt:53
```

I will open relevant tickets for the missing functionality

**Comment by d0c-s4vage** [comment]
@RagingPotatoz the MP4.bt version you referenced (v2.2) works now, as does the latest version v(3.3):

v2.2 output:

```text
$> pfp -t MP4.v2.2.bt /home/james/Downloads/test_video.mp4
struct {
    box        = struct {
        size       = UInt(159 [0000009f])
        type       = union {
            text       = Char[4] ('moov')
        }
        box        = struct[2]
            box[0] = struct {
                    size       = UInt(108 [0000006c])
                    type       = union {
                        text       = Char[4] ('mvhd')
                    }
                    version    = Char(0 [00])
                    flags      = Char[3] ('\x00\x00\x00')
                    crTime     = UInt(3648061658 [d97100da])
                    mdTime     = UInt(3648061658 [d97100da])
                    tmScale    = UInt(90000 [00015f90])
                    duration   = UInt(0 [00000000])
                    rest       = Char[80] ('\x00\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00')
                }
            box[1] = struct {
                    size       = UInt(43 [0000002b])
                    type       = union {
                        text       = Char[4] ('udta')
                    }
                    rest       = Char[35] ('\x00\x00\x00#©enc\x00\x17\x00\x00vlc 3.0.')
                }
    }
}
```

and the v3.3 output:

```text
$> pfp -t MP4.v3.3.bt /home/james/Downloads/test_video.mp4
struct {
    box        = struct {
        bh         = struct {
            size       = UInt(159 [0000009f])
            type       = struct {
                value      = Char[4] ('moov')
            }
        }
        box_0      = struct {
            bh         = struct {
                size       = UInt(108 [0000006c])
                type       = struct {
                    value      = Char[4] ('mvhd')
                }
            }
            version    = Char(0 [00])
            flags      = Char[3] ('\x00\x00\x00')
            create_time = struct {
                value      = UInt(3648061658 [d97100da])
            }
            modify_time = struct {
                value      = UInt(3648061658 [d97100da])
            }
            time_scale = UInt(90000 [00015f90])
            duration   = UInt(0 [00000000])
            preferred_rate = struct {
                value      = Int(65536 [00010000])
            }
            preferred_volume = struct {
                value      = Short(256 [0100])
            }
            reserved   = Char[10] ('\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
            matrix_structure = struct {
                a          = struct {
                    value      = Int(65536 [00010000])
                }
                b          = struct {
                    value      = Int(0 [00000000])
                }
                u          = struct {
                    value      = Int(0 [00000000])
                }
                c          = struct {
                    value      = Int(0 [00000000])
                }
                d          = struct {
                    value      = Int(65536 [00010000])
                }
                v          = struct {
                    value      = Int(0 [00000000])
                }
                x          = struct {
                    value      = Int(0 [00000000])
                }
                y          = struct {
                    value      = Int(0 [00000000])
                }
                w          = struct {
                    value      = Int(1073741824 [40000000])
                }
            }
            preview_time = UInt(0 [00000000])
            preview_duration = UInt(0 [00000000])
            poster_time = UInt(0 [00000000])
            selection_time = UInt(0 [00000000])
            selection_duration = UInt(0 [00000000])
            current_time = UInt(0 [00000000])
            next_track_id = UInt(1 [00000001])
        }
        _skipped_0 = Char[0] ('')
        box_1      = struct {
            bh         = struct {
                size       = UInt(43 [0000002b])
                type       = struct {
                    value      = Char[4] ('udta')
                }
            }
            box        = struct {
                bh         = struct {
                    size       = UInt(35 [00000023])
                    type       = struct {
                        value      = Char[4] ('©enc')
                    }
                }
                _skipped   = Char[27] ('\x00\x17\x00\x00vlc 3.0.4 stream')
            }
            _skipped   = Char[0] ('')
        }
        _skipped_1 = Char[0] ('')
    }
}
```

And the test mp4 I used (rename to .mp4 instead of .mp4.txt): [test_video.mp4.txt](https://github.com/d0c-s4vage/py010parser/files/4024736/test_video.mp4.txt)
