### ISSUE TITLE
Parser aborts on empty structure

### ISSUE THREAD

**Issue by synalysis** [d0c-s4vage/py010parser#8]
The parser aborts in line 234 of the template http://www.sweetscape.com/010editor/templates/files/EXETemplate.bt because of an empty structure.

py010parser.plyparser.ParseError: /var/folders/r9/lsnl52fx7tzc884cyvyrlpdr0000gn/T/tmp6G1Evt:234:40: before: }

**Comment by d0c-s4vage** [comment]
That's an interesting one. I'll look at this this week. Thanks!

**Comment by d0c-s4vage** [comment]
```
Traceback (most recent call last):
  File "test_basic_parse.py", line 520, in test_exe_template
    res = parse_file(template_path("EXETemplate.bt"))
  File "../py010parser/__init__.py", line 97, in parse_file
    return parser.parse(text, filename, predefine_types=predefine_types, keep_scopes=keep_scopes)
  File "../py010parser/c_parser.py", line 172, in parse
    debug=debuglevel)
  File "../py010parser/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "../py010parser/ply/yacc.py", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "../py010parser/c_parser.py", line 1966, in p_error
    column=self.clex.find_tok_column(p)))
  File "../py010parser/plyparser.py", line 54, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
ParseError: templates/EXETemplate.bt:234:40: before: }
```

**Comment by d0c-s4vage** [comment]
line 234

``` c
                                struct{} VersionInfoStructure;
```
