### ISSUE TITLE
_structs_with_params is not being reset along with the scope_stack

### ISSUE THREAD

**Issue by d0c-s4vage** [d0c-s4vage/py010parser#9]
This test from pfp (https://github.com/d0c-s4vage/pfp/blob/d6e9bad/tests/test_struct_union.py#L136-L152) is now failing, while the same test succeeds in py010parser (https://github.com/d0c-s4vage/py010parser/blob/011e6c0/tests/test_basic_parse.py#L27-L40).

The test:

``` c
typedef union {
    int some_int;
    struct {
        char a;
        char b;
        char c;
        char d;
    } some_chars;
} blah;
blah some_union;
```

It might have something to do with `predefine_types` being `True`/`False`, or maybe with the preprocessor. The code hasn't changed since the tests were passing ~a year ago, but the tests fail when run on a new laptop; this makes me think it's more likely a change in the preprocessor.

The full error text:

```
======================================================================
ERROR: test_union (__main__.TestStructUnion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_struct_union.py", line 151, in test_union
    """
  File "/home/james/__ws__/dev/pfp/tests/utils.py", line 14, in _test_parse_build
    dom = pfp.parse(six.StringIO(data), template, debug=debug, predefines=predefines)
  File "../pfp/__init__.py", line 64, in parse
    dom = interp.parse(data, template, predefines=predefines, orig_filename=orig_filename, keep_successful=keep_successful)
  File "../pfp/interp.py", line 672, in parse
    self._ast = self._parse_string(template, predefines)
  File "../pfp/interp.py", line 816, in _parse_string
    keep_scopes=predefines
  File "/usr/local/lib/python2.7/dist-packages/py010parser/__init__.py", line 113, in parse_string
    return parser.parse(text, filename, predefine_types=predefine_types, keep_scopes=keep_scopes)
  File "/usr/local/lib/python2.7/dist-packages/py010parser/c_parser.py", line 168, in parse
    debug=debuglevel)
  File "/usr/local/lib/python2.7/dist-packages/py010parser/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/usr/local/lib/python2.7/dist-packages/py010parser/ply/yacc.py", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/usr/local/lib/python2.7/dist-packages/py010parser/c_parser.py", line 1962, in p_error
    column=self.clex.find_tok_column(p)))
  File "/usr/local/lib/python2.7/dist-packages/py010parser/plyparser.py", line 54, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
ParseError: /tmp/tmpl6dM9f:12:32: before: ;
```

**Comment by d0c-s4vage** [comment]
Found out that this has to do with some state from a previous test being left over and messing up the test in pfp. Still figuring out what the problem is, but if I run the test individually:

``` bash
python test_struct_union.py TestStructUnion.test_union
python3 test_struct_union.py TestStructUnion.test_union
```

The single tests above pass, but running the entire test_struct_union.py file fails.

This may be a problem in pfp instead of in py010parser.

**Comment by d0c-s4vage** [comment]
pfp creates a single `py010parser.c_parser.CParser()` object to do all of its parsing.

If the `pfp.PARSER` object is set to a new `CParser()` at the beginning of the failing test, the test passes:

``` python
    def test_union(self):
        import py010parser
        pfp.PARSER = py010parser.c_parser.CParser()
        dom = self._test_parse_build(
            "abcd",
            """
                typedef union {
                    int some_int;
                    struct {
                        char a;
                        char b;
                        char c;
                        char d;
                    } some_chars;
                } blah;

                blah some_union;
            """
        )

```

 Some state is being carried over from previous parsings that is causing the problem.

pfp only uses a single parser, as the overhead of creating a new one and loading the `lextab.py` and `yacctab.py` files is significant.

**Comment by d0c-s4vage** [comment]
This was an extremely interesting issue, especially the reasons as to why this bug was triggered now and not a year ago (no code changes since then). I suspect it may have been due to a different ordering of the test methods in the TestUnionStruct class, perhaps due to a change in the Python `dict` implementation since a year ago.

Curiosity compels me to figure this out.

**Comment by d0c-s4vage** [comment]
Forgot to add a unit test for this bug, reopening

**Comment by d0c-s4vage** [comment]
Also, it's not the Python versions, 2.7.9 was run a year ago, as well as now (now: https://travis-ci.org/d0c-s4vage/pfp/jobs/158657960 and a year ago: https://travis-ci.org/d0c-s4vage/pfp/jobs/77479532)
